development: &development
  adapter: postgresql
  host: localhost
  database: nomorerack_development
  username: <%= `whoami` %>
  password:
  min_messages: warning

test:
  <<: *development
  database: nomorerack_test

production:
  <<: *development
